const docsConfig = [
  {
    category: "Coding Test Preparation",
    pages: [
      { title: "Preparation Home & Strategy", path: "CodingTestPreparation/coding_test_preparation" },
      // { title: "Basic — C++ Fundamentals", path: "CodingTestPreparation/Basic/01_cpp_fundamentals" },
      // { title: "Basic — Functions", path: "CodingTestPreparation/Basic/02_functions" },
      // { title: "Basic — Arrays", path: "CodingTestPreparation/Basic/03_arrays" },
      // { title: "Basic — Strings", path: "CodingTestPreparation/Basic/04_strings" },
      // { title: "Basic — Pointers & References", path: "CodingTestPreparation/Basic/05_pointers_and_references" },
      // { title: "Basic — Recursion Basics", path: "CodingTestPreparation/Basic/06_recursion_basics" },
      // { title: "Basic — Basic OOP", path: "CodingTestPreparation/Basic/07_basic_oop" },
      // { title: "Basic — STL Basics", path: "CodingTestPreparation/Basic/08_stl_basics" },
      // { title: "Basic — Complexity Basics", path: "CodingTestPreparation/Basic/09_complexity_basics" },
      // { title: "Basic — Data Structures", path: "CodingTestPreparation/Basic/10_basic_data_structures" },
      // { title: "Basic — Searching & Sorting", path: "CodingTestPreparation/Basic/11_searching_and_sorting" },
      // { title: "Basic — Math & Implementation", path: "CodingTestPreparation/Basic/12_math_and_implementation" },
      // { title: "Standard — Intermediate C++", path: "CodingTestPreparation/Standard/01_intermediate_cpp" },
      // { title: "Standard — Practical STL", path: "CodingTestPreparation/Standard/02_practical_stl" },
      // { title: "Standard — Lists, Trees, BST", path: "CodingTestPreparation/Standard/03_linked_list_trees_bst" },
      // { title: "Standard — Heap, Trie, Graph", path: "CodingTestPreparation/Standard/04_heap_trie_graph" },
      // { title: "Standard — Binary Search Patterns", path: "CodingTestPreparation/Standard/05_binary_search_patterns" },
      // { title: "Standard — Two Pointers", path: "CodingTestPreparation/Standard/06_two_pointers" },
      // { title: "Standard — Sliding Window", path: "CodingTestPreparation/Standard/07_sliding_window" },
      // { title: "Standard — Hashing", path: "CodingTestPreparation/Standard/08_hashing" },
      // { title: "Standard — Greedy Basics", path: "CodingTestPreparation/Standard/09_greedy_basics" },
      // { title: "Standard — DFS & BFS", path: "CodingTestPreparation/Standard/10_dfs_bfs" },
      // { title: "Standard — Union-Find", path: "CodingTestPreparation/Standard/11_union_find" },
      // { title: "Standard — DP Basics", path: "CodingTestPreparation/Standard/12_dp_basics" },
      // { title: "Standard — Medium Patterns", path: "CodingTestPreparation/Standard/13_medium_interview_patterns" },
      // { title: "Advanced — Modern C++", path: "CodingTestPreparation/Advanced/01_modern_advanced_cpp" },
      // { title: "Advanced — Smart Ptrs & RAII", path: "CodingTestPreparation/Advanced/02_smart_pointers_move_raii" },
      // { title: "Advanced — STL Internals", path: "CodingTestPreparation/Advanced/03_advanced_stl" },
      // { title: "Advanced — Segment & Fenwick", path: "CodingTestPreparation/Advanced/04_segment_fenwick_sparse" },
      // { title: "Advanced — Graph Algorithms", path: "CodingTestPreparation/Advanced/05_advanced_graph" },
      // { title: "Advanced — Advanced DP", path: "CodingTestPreparation/Advanced/06_advanced_dp" },
      // { title: "Advanced — String Algorithms", path: "CodingTestPreparation/Advanced/07_string_algorithms" },
      // { title: "Advanced — Number Theory", path: "CodingTestPreparation/Advanced/08_number_theory" },
      // { title: "Advanced — Combinatorics", path: "CodingTestPreparation/Advanced/09_combinatorics" },
      // { title: "Advanced — Concurrency", path: "CodingTestPreparation/Advanced/10_concurrency_basics" },
      // { title: "Advanced — Low-Level Design", path: "CodingTestPreparation/Advanced/11_low_level_design" },
      // { title: "Advanced — Hard Patterns", path: "CodingTestPreparation/Advanced/12_hard_interview_patterns" },
    ],
  },
  {
    category: "SQL",
    pages: [
      { title: "MySQL Functions", path: "SQL/functions" },
      { title: "Query Filtering", path: "SQL/query_filtering" },
    ],
  },
  {
    category: "AWS",
    pages: [
      { title: "AWS Certification Types", path: "AWS/certificationTypes" },
    ],
  },
  {
    category: "OOP",
    pages: [
      { title: "OOP Core Principles in Python", path: "OOP/principles" },
      { title: "OOP Core Concepts in Java", path: "OOP/CoreConcepts" },
      { title: "Interfaces, Abstract Classes & Access Modifiers", path: "OOP/CoreConceptsPart2" },
      { title: "Design Patterns", path: "OOP/design_patterns" },
    ],
  },
  {
    category: "Data Structures",
    pages: [
      { title: "Arrays & Strings", path: "DataStructures/arrays_and_strings" },
      { title: "C++ Arrays & Vectors", path: "DataStructures/arrays_and_vectors_cpp" },
      { title: "Linked Lists", path: "DataStructures/linked_lists" },
      { title: "Trees & Graphs", path: "DataStructures/trees_and_graphs" },
    ],
  },
];

export default docsConfig;
